demo.ipynb
src/MeshCat.jl
src/commands.jl
src/lowering.jl
src/servers/trees.jl
src/servers/zmqserver.jl
src/visualizer.jl
test/runtests.jl

Equivalent of https://github.com/rdeits/meshcat-python/pull/6

Have zmq server remember entire scene tree

---

.travis.yml
test/REQUIRE

require meshing 0.3 for test

---

src/servers/zmqserver.jl
src/visualizer.jl

due to https://github.com/JuliaInterop/ZMQ.jl/issues/167

turn off multipart messaging 

---

REQUIRE
animation.ipynb
demo.ipynb
src/MeshCat.jl
src/abstract_visualizer.jl
src/animation_visualizer.jl
src/animations.jl
src/commands.jl
src/lowering.jl
src/trees.jl
src/visualizer.jl
test/notebook.jl
test/paths.jl
test/runtests.jl
test/visualizer.jl

Support the new meshcat animation interface

---

.gitmodules
.travis.yml
assets/.gitignore
deps/build.jl
src/MeshCat.jl
src/animations.jl
src/download_helpers.jl

Download meshcat assets rather than relying on a git submodule

---

src/lowering.jl
test/REQUIRE
test/runtests.jl
test/visualizer.jl

This removes a lot of test dependencies and should make testing faster and more stable.

replace Polyhedra.jl test with a simpler test for custom primitives

---

.travis.yml
REQUIRE
deps/build.jl
src/MeshCat.jl
src/animations.jl
src/objects.jl
src/servers.jl
src/trees.jl
src/visualizer.jl
test/REQUIRE
test/notebook.jl
test/runtests.jl

Rebased your branch and added some fixes. Currently stuck on WebIO.
For `send`, I don't think it's a good idea to extend `Sockets.send` (`wait` is kind of iffy too IMO).

Towards v0.7 support

---

.gitignore
.travis.yml

Again, against the rd/0.7-support branch.

CI + gitignore updates

---

.gitignore
.travis.yml
REQUIRE
appveyor.yml
demo.ipynb
deps/build.jl
src/MeshCat.jl
src/lowering.jl
src/msgpack.jl
src/servers.jl
src/trees.jl
test/runtests.jl
test/visualizer.jl

Waiting on:
This needs HTTP.jl master, Mux.jl with https://github.com/JuliaWeb/Mux.jl/pull/66 , WebSockets.jl master, WebIO.jl with https://github.com/JuliaGizmos/WebIO.jl/pull/169 , Meshing.jl with https://github.com/JuliaGeometry/Meshing.jl/pull/16 GeometryTypes.jl master, and probably a few more packages that I'm forgetting, but it does actually work. 
There are a couple of deprecations left in the notebook files. I'll get around to those eventually.

Support Julia 0.7

---

Readme.md

My editor does that automatically, I thought I could make a PR out of it ^^

Remove trailing whitespace in README

---

Readme.md

Changes the example to reflect changes in Polyhedra. See https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/130

Update README example with Polyhedra

---

.travis.yml
REQUIRE
appveyor.yml
deps/build.jl
src/MeshCat.jl
src/animations.jl
src/geometry.jl
src/msgpack.jl
src/servers.jl
src/trees.jl
test/runtests.jl
test/visualizer.jl

Drop Julia 0.6

---

REQUIRE

Ref #71 https://github.com/JuliaGizmos/WebIO.jl/issues/225

upper-bound WebIO

---

deps/build.jl
src/lowering.jl
src/visualizer.jl
test/runtests.jl
test/scenes.jl
test/visualizer.jl

update to the newest meshcat js

---

.travis.yml

Seems to have been broken when we dropped Julia 0.6

try to fix coverage detection

---

.travis.yml
Manifest.toml
Project.toml
REQUIRE
demo.ipynb

Support WebIO 0.7 and add project and manifest files

---

src/MeshCat.jl
src/objects.jl
test/visualizer.jl

Add Line and LineLoop and make constructing them easier

---

src/MeshCat.jl
src/servers.jl

Maybe do something like this to access from other than localhost

Allow the user to change listen address

---

Manifest.toml
Project.toml
appveyor.yml
notebooks/Manifest.toml
notebooks/demo.ipynb
src/visualizer.jl

Update to WebIO v0.8.x

---

src/visualizer.jl

* Adapt to `WebIO.ensure_connection` changes
* fix waiting forever when a lot of geometries are loaded without an open visualizer by increasing outbox size.

[PR against rd/update-js] updates to match WebIO.

---

deps/build.jl

Update meshcat to get https://github.com/rdeits/meshcat/pull/64

---

deps/build.jl

Adds https://github.com/rdeits/meshcat/pull/61

Update meshcat js

---

deps/build.jl
src/MeshCat.jl
src/lowering.jl
test/scenes.jl

Update meshcat js to suppport controlling the background

---

deps/build.jl
src/MeshCat.jl
src/commands.jl
src/lowering.jl
src/visualizer.jl

Hi, @rdeits! :slightly_smiling_face: Hope you are doing well. I have taken the initiative to implement #61. This is just a proposal, so feel free to go over my changes and review them as you wish. It goes in hand with [rdeits/meshcat#79](https://github.com/rdeits/meshcat/pull/79).

[Draft] Adds `TakeScreenshot` command

---

.github/workflows/ci.yml
Artifacts.toml
notebooks/Static HTML Visualizers.ipynb
notebooks/animation.ipynb
notebooks/demo.ipynb
test/visualizer.jl

See: https://github.com/rdeits/meshcat/pull/109

Update meshcat to get animation fixes

---

Readme.md
notebooks/demo.ipynb

Fixes https://github.com/rdeits/MeshCat.jl/issues/239
We already had a working example in the demo jupyter notebook, so I just had to clean up that notebook and copy the example back to the readme.

Fix contour function example in the readme

---

src/animations.jl

Should solve https://github.com/rdeits/MeshCat.jl/issues/194

Add optional video conversion arguments

---

Project.toml

Patch version increase did not work — https://github.com/JuliaRegistries/General/pull/120651#issuecomment-2516555079

Bump minor version digit
