rdeits/MeshCat.jl

deps/build.jl

Should improve reliability for users without git installed

use Base.LibGit2 to do submodule update instead of relying on system git

---

demo.ipynb
src/MeshCat.jl

Also fixes notebooks.
I do get a nasty inference error on 1.0 though, but tests pass regardless.
```julia
Internal error: encountered unexpected error in runtime:
TypeError(func=:<:, context="", expected=Type{T} where T, got=_)
rec_backtrace at /buildworker/worker/package_linux64/build/src/stackwalk.c:94
record_backtrace at /buildworker/worker/package_linux64/build/src/task.c:246
jl_throw at /buildworker/worker/package_linux64/build/src/task.c:577
jl_type_error_rt at /buildworker/worker/package_linux64/build/src/rtutils.c:118
jl_type_error at /buildworker/worker/package_linux64/build/src/rtutils.c:124
jl_f_issubtype at /buildworker/worker/package_linux64/build/src/builtins.c:407
tuplemerge at ./compiler/typelimits.jl:422
tmerge at ./compiler/typelimits.jl:363
getfield_tfunc at …
```

Fixes for 1.0

---

src/MeshCat.jl

More helpful error message when main.min.js can't be found.

---

src/servers.jl

In Julia 1.0.2 `run` seems not be be working with command prompt builtin commands. 
In particular I get this error: 
~~~
julia> vis = Visualizer()
MeshCat Visualizer with path /meshcat
julia> open(vis)
[ Info: Serving MeshCat visualizer at http://127.0.0.1:8700
[ Info: Listening on: Sockets.InetAddr{Sockets.IPv4}(ip"127.0.0.1", 0x21fc)
Could not open browser automatically: Base.IOError("could not spawn `start http://127.0.0.1:8700`: n
o such file or directory (ENOENT)", -4058)
Please open the following URL in your browser:
http://127.0.0.1:8700
~~~
Explicitly launching the command prompt executable `cmd.exe` that executes the builtin `start` command with the `/C` option seems to be working fine instead. See https://github.com/JuliaLang/julia/issues/23597 for a related discussion.

Fix open_url on Windows

---

src/servers.jl

It would prefer the `open()` function not starting the browser, so I added a keyword to skip that part. The default behaviour does not change. The keyword is: `start_browser`, I have several other ideas (`open_url` or `open_browser` or `open_in_browser`), but could not select from them, because the function is `open()` and adding a kwarg like `open_...` seems odd.
I have concerns  about type instability at the `start_browser && open_url(url)` line, but don't know if it's true and/or it is a problem, as it (in theory) runs once per session.
I also didn't included it into the demo or docs, because the other kwargs are also excluded.

Add keyword for starting the browser

---

src/MeshCat.jl
src/servers.jl

This PR builds on top of #86 and fixes the merge conflicts that I recently introduced into master. It also adds some documentation for the `open()` function.

Add `host` kwarg to `open()` and add some documentation

---

Manifest.toml
Project.toml
REQUIRE

With MeshCat `dev`ed, I was getting the following:
```julia
using MeshCat
WARNING: could not import HTTP.HandlerFunction into Mux
ERROR: LoadError: LoadError: UndefVarError: Server not defined
Stacktrace:
[1] top-level scope at none:0
[2] include at ./boot.jl:326 [inlined]
[3] include_relative(::Module, ::String) at ./loading.jl:1038
[4] include at ./sysimg.jl:29 [inlined]
[5] include(::String) at /home/twan/.julia/packages/Mux/11dSG/src/Mux.jl:1
[6] top-level scope at none:0
[7] include at ./boot.jl:326 [inlined]
[8] include_relative(::Module, ::String) at ./loading.jl:1038
[9] include(::Module, ::String) at ./sysimg.jl:29
[10] top-level scope at none:2
[11] eval at ./boot.jl:328 [inlined]
[12] eval(::Expr) at ./client.jl:404
[13] top-level scope at ./none:3
in expression starting at …
```

Update Mux to be compatible with HTTP 0.8.

---

src/MeshCat.jl
src/abstract_visualizer.jl
test/visualizer.jl

 Add hide! utility function. 

---

src/visualizer.jl

Existing code was relying on an implementation detail where `iframe.scope.dom.props[:style]` was set (in particular it had `overflow: none`). The WebIO rework doesn't set this by default, which causes an error when using `WebIO#master`.

Set default value for iframe style dict.

---

src/visualizer.jl

Minor change on top of #100 which avoids a couple of extra Dict allocations by using `get!` instead of `get`

Avoid some dict lookups and a few allocations

---

src/MeshCat.jl
src/animation_visualizer.jl
src/arrow_visualizer.jl
src/lowering.jl
test/visualizer.jl

(On top of #96).
Adds an `ArrowVisualizer` type, which enables easy visualization of 3D arrows consisting of a cylinder for the shaft and a cone for the head.
I took inspiration from `MechanismVisualizer`, in that `ArrowVisualizer` is basically a cheap-to-construct abstraction layer around a `Visualizer` (in this case two `Visualizer`s) with a higher-level interface for setting the transforms.
One issue is that this doesn't work with `AnimationVisualizer` quite yet, because the transformations I'm computing aren't rigid transformations, and so trying to extract out just the translation and rotation doesn't work. @rdeits, what do you think about this? It's quite unfortunate that we have to decompose the transform in this way; can't we just set the matrix directly when creating animations? …

 Add ArrowVisualizer

---

src/lowering.jl
src/objects.jl

Hey, @rdeits! I have added `linewidth` to `GenericMaterial`. Let me know if you think `linewidth` is not generic enough and, in that case, whether a new subtype of `AbstractMaterial` should be added. Thanks!

Adds `linewidth` param to GenericMaterial.

---

src/arrow_visualizer.jl
test/visualizer.jl

Avoid the inverse, which was causing a `SingularException` when the shaft length was computed to be zero. 
Basically, turn
```
vis -> shaft -> head
```
into
```
vis -> shaft
-> head
```
where only the translation and rotation part of the old shaft transform is now applied to `vis`.
I've verified that the animation interpolation still looks fine.
Fixes #105.

Fix visualization of arrows with zero shaft length.

---

src/visualizer.jl

The current implementation is broken because connections are lazily added to `ConnectionPool.connections`. Related to (but not dependent on) https://github.com/JuliaGizmos/WebIO.jl/pull/265.

Change implementation of wait.

---

src/visualizer.jl
test/runtests.jl
test/wait.jl

I haven't been able to figure out what the *actual* problem is, but the recent change to `wait()` is causing it to block under certain conditions (see https://github.com/rdeits/MeshCat.jl/pull/99#issuecomment-509067108 ). This change is a gross work-around.

work-around for race condition in `wait()`

---

Manifest.toml
Project.toml

0.2.5. contains https://github.com/jrevels/Cassette.jl/pull/137, which
we ran into when using Cassette-based animation in MeshCatMechanisms.
Might as well lower-bound Cassette here, as other dependencies could run
into the same issue, and it doesn't really make sense to add Cassette as
a direct dependency to MeshCatMechanisms just to lower-bound it.

Add lower bound on Cassette.

---

src/MeshCat.jl
src/animations.jl
src/atframe.jl
src/lowering.jl
src/util.jl
test/runtests.jl
test/util.jl
test/visualizer.jl

On top of #112.
Needs tests, but seems to be working fine for me. Just wanted to open this for review and so that I don't forget.

Add merge! for animation types, insert! for AnimationTrack. 

---

src/arrow_visualizer.jl

`settransform!` function with the signature for two points was not propagating kwargs

Adds missing `kwargs` propagation in `arrow_visualizer.jl`

---

src/lowering.jl
src/objects.jl

Resolves #152 
Here's a demo of using the new properties to show a mesh, its wireframe, and its vertices:
```julia
using MeshCat
using MeshIO, FileIO
using Colors
using GeometryTypes: vertices
function draw_fancy_mesh(vis::Visualizer, mesh)
setobject!(vis[:mesh], cube, MeshPhongMaterial())
setobject!(vis[:wireframe], cube, MeshPhongMaterial(
wireframe=true,
wireframeLinewidth=2,
color=colorant"black"))
setobject!(vis[:vertices], PointCloud(vertices(cube)),
PointsMaterial(size=0.05))
end
vis = Visualizer()
open(vis)
cube = load("test/data/meshes/cube.stl")
draw_fancy_mesh(vis[:cube], cube)
```

Handle the wireframe and wireframeLinewidth properties

---

src/MeshCat.jl

Brings RotMatrix from Rotations.jl into scope

---

src/visualizer.jl

Correctly pass through `core.host` to the server

---

src/servers.jl

Restore the option to not open a browser as it was pre #141 
I use this functionality, but I'm open to other ways of doing it. Also see #84

Restore start_browser kwarg from v0.9

---

Project.toml

Add StaticArrays v1.0. All tests passed for me, and I don't think the changes affect anything in MeshCat.

Allow StaticArrays v1.0

---

src/MeshCat.jl
src/arrow_visualizer.jl
src/atframe.jl

See Rotations.jl v1.1.0 (https://github.com/JuliaGeometry/Rotations.jl/releases/tag/v1.1.0).

Renames `UnitQuaternion` to `QuatRotation`

---

.github/workflows/ci.yml
Project.toml

Constraining WebSockets.jl to versions <1.6 fixes #234 ~but is also causing the Windows CI pipeline to fail~.
**Edit 1:** Actually, this is not the breaking change. Something else must have broken the pipeline, because after having run the pipeline for the previous master today, that one is failing too (when previously it was succeeding).
**Edit 2:** I have decided to temporarily disable the Windows runner from the CI and move the task for fixing it to #236.

Constrain WebSockets.jl version to <1.6

---

.github/workflows/ci.yml
Project.toml
src/MeshCat.jl
src/animations.jl

This was intended to help with #236 by avoiding requiring 7z.exe to unpack .tar files. It doesn't actually fix the Windows CI issue (see https://github.com/rdeits/MeshCat.jl/pull/240#issuecomment-1547104219 ), but I think it's still a good idea. Tar.jl seems better-maintained than BinDeps.jl, and I'd rather not rely on the existence of 7z.exe anyway.

Replace BinDeps.jl with Tar.jl

---

Project.toml
notebooks/animation.ipynb
src/MeshCat.jl
src/animations.jl
src/atframe.jl
src/visualizer.jl
test/visualizer.jl

@ferrolho I was inspired by your question from https://github.com/rdeits/MeshCat.jl/pull/255#discussion_r1811278392 to try to get rid of Cassette. It's a super cool tool, but probably not worth the complexity for our very minor usage. 
This PR is the best I could come up with today as a way to (mostly) preserve the animation system without using Cassette. It adds a stack of `AnimationContext`s to the `CoreVisualizer`. That stack is empty by default, but `atframe()` pushes a new `(animation, frame)` context onto the stack before calling the user's provided function. This causes any `setprop!` or `settransform!` calls to be redirected to that animation, which is exactly what we had before with Cassette. 
Unfortunately, I do need to make a breaking change to the API: You now have to do …

Drop Cassette.jl by rewriting animation handlers
